# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: c:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/ARTY_ETH/ARTY_ETH.gen/sources_1/bd/design_2_udp/ip/design_2_udp_axi_ethernet_0_0/bd_0/ip/ip_2/bd_972b_c_shift_ram_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_972b_c_shift_ram_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/ARTY_ETH/ARTY_ETH.gen/sources_1/bd/design_2_udp/ip/design_2_udp_axi_ethernet_0_0/bd_0/ip/ip_2/bd_972b_c_shift_ram_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_972b_c_shift_ram_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
