# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Arty-A7-35-Master.xdc

# Block Designs: bd/arty_adc_eth_v4/arty_adc_eth_v4.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4 || ORIG_REF_NAME==arty_adc_eth_v4} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_clk_wiz_0_0/arty_adc_eth_v4_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_clk_wiz_0_0 || ORIG_REF_NAME==arty_adc_eth_v4_clk_wiz_0_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_mig_7series_0_0/arty_adc_eth_v4_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_mig_7series_0_0 || ORIG_REF_NAME==arty_adc_eth_v4_mig_7series_0_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_microblaze_0_0/arty_adc_eth_v4_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_microblaze_0_0 || ORIG_REF_NAME==arty_adc_eth_v4_microblaze_0_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_dlmb_v10_0/arty_adc_eth_v4_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_dlmb_v10_0 || ORIG_REF_NAME==arty_adc_eth_v4_dlmb_v10_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_ilmb_v10_0/arty_adc_eth_v4_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_ilmb_v10_0 || ORIG_REF_NAME==arty_adc_eth_v4_ilmb_v10_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_dlmb_bram_if_cntlr_0/arty_adc_eth_v4_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==arty_adc_eth_v4_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_ilmb_bram_if_cntlr_0/arty_adc_eth_v4_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==arty_adc_eth_v4_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_lmb_bram_0/arty_adc_eth_v4_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_lmb_bram_0 || ORIG_REF_NAME==arty_adc_eth_v4_lmb_bram_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_xbar_0/arty_adc_eth_v4_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_xbar_0 || ORIG_REF_NAME==arty_adc_eth_v4_xbar_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_microblaze_0_axi_periph_0/arty_adc_eth_v4_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_microblaze_0_axi_periph_0 || ORIG_REF_NAME==arty_adc_eth_v4_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_microblaze_0_axi_intc_0/arty_adc_eth_v4_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_microblaze_0_axi_intc_0 || ORIG_REF_NAME==arty_adc_eth_v4_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_microblaze_0_xlconcat_0/arty_adc_eth_v4_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_microblaze_0_xlconcat_0 || ORIG_REF_NAME==arty_adc_eth_v4_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_mdm_1_0/arty_adc_eth_v4_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_mdm_1_0 || ORIG_REF_NAME==arty_adc_eth_v4_mdm_1_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_axi_ethernetlite_0_0/arty_adc_eth_v4_axi_ethernetlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_axi_ethernetlite_0_0 || ORIG_REF_NAME==arty_adc_eth_v4_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_axi_uartlite_0_0/arty_adc_eth_v4_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_axi_uartlite_0_0 || ORIG_REF_NAME==arty_adc_eth_v4_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_axi_timer_0_0/arty_adc_eth_v4_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_axi_timer_0_0 || ORIG_REF_NAME==arty_adc_eth_v4_axi_timer_0_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_xadc_wiz_0_0/arty_adc_eth_v4_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_xadc_wiz_0_0 || ORIG_REF_NAME==arty_adc_eth_v4_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_rst_clk_wiz_0_100M_0/arty_adc_eth_v4_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==arty_adc_eth_v4_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_auto_pc_5/arty_adc_eth_v4_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_auto_pc_5 || ORIG_REF_NAME==arty_adc_eth_v4_auto_pc_5} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_auto_us_0/arty_adc_eth_v4_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_auto_us_0 || ORIG_REF_NAME==arty_adc_eth_v4_auto_us_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_auto_us_1/arty_adc_eth_v4_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_auto_us_1 || ORIG_REF_NAME==arty_adc_eth_v4_auto_us_1} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_auto_us_2/arty_adc_eth_v4_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_auto_us_2 || ORIG_REF_NAME==arty_adc_eth_v4_auto_us_2} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_auto_ds_0/arty_adc_eth_v4_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_auto_ds_0 || ORIG_REF_NAME==arty_adc_eth_v4_auto_ds_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_auto_pc_0/arty_adc_eth_v4_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_auto_pc_0 || ORIG_REF_NAME==arty_adc_eth_v4_auto_pc_0} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_auto_ds_1/arty_adc_eth_v4_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_auto_ds_1 || ORIG_REF_NAME==arty_adc_eth_v4_auto_ds_1} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_auto_pc_1/arty_adc_eth_v4_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_auto_pc_1 || ORIG_REF_NAME==arty_adc_eth_v4_auto_pc_1} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_auto_ds_2/arty_adc_eth_v4_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_auto_ds_2 || ORIG_REF_NAME==arty_adc_eth_v4_auto_ds_2} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_auto_pc_2/arty_adc_eth_v4_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_auto_pc_2 || ORIG_REF_NAME==arty_adc_eth_v4_auto_pc_2} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_auto_ds_3/arty_adc_eth_v4_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_auto_ds_3 || ORIG_REF_NAME==arty_adc_eth_v4_auto_ds_3} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_auto_pc_3/arty_adc_eth_v4_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_auto_pc_3 || ORIG_REF_NAME==arty_adc_eth_v4_auto_pc_3} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_auto_ds_4/arty_adc_eth_v4_auto_ds_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_auto_ds_4 || ORIG_REF_NAME==arty_adc_eth_v4_auto_ds_4} -quiet] -quiet

# IP: bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_auto_pc_4/arty_adc_eth_v4_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_adc_eth_v4_auto_pc_4 || ORIG_REF_NAME==arty_adc_eth_v4_auto_pc_4} -quiet] -quiet

# XDC: c:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/project_2/project_2.gen/sources_1/bd/arty_adc_eth_v4/arty_adc_eth_v4_ooc.xdc
