# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Arty-A7-35-Master.xdc

# Block Designs: bd/eth_mac_test/eth_mac_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test || ORIG_REF_NAME==eth_mac_test} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_mig_7series_0_0/eth_mac_test_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_mig_7series_0_0 || ORIG_REF_NAME==eth_mac_test_mig_7series_0_0} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_microblaze_0_0/eth_mac_test_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_microblaze_0_0 || ORIG_REF_NAME==eth_mac_test_microblaze_0_0} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_dlmb_v10_0/eth_mac_test_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_dlmb_v10_0 || ORIG_REF_NAME==eth_mac_test_dlmb_v10_0} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_ilmb_v10_0/eth_mac_test_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_ilmb_v10_0 || ORIG_REF_NAME==eth_mac_test_ilmb_v10_0} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_dlmb_bram_if_cntlr_0/eth_mac_test_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==eth_mac_test_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_ilmb_bram_if_cntlr_0/eth_mac_test_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==eth_mac_test_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_lmb_bram_0/eth_mac_test_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_lmb_bram_0 || ORIG_REF_NAME==eth_mac_test_lmb_bram_0} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_xbar_0/eth_mac_test_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_xbar_0 || ORIG_REF_NAME==eth_mac_test_xbar_0} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_microblaze_0_axi_periph_0/eth_mac_test_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_microblaze_0_axi_periph_0 || ORIG_REF_NAME==eth_mac_test_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_microblaze_0_axi_intc_0/eth_mac_test_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_microblaze_0_axi_intc_0 || ORIG_REF_NAME==eth_mac_test_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_microblaze_0_xlconcat_0/eth_mac_test_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_microblaze_0_xlconcat_0 || ORIG_REF_NAME==eth_mac_test_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_mdm_1_0/eth_mac_test_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_mdm_1_0 || ORIG_REF_NAME==eth_mac_test_mdm_1_0} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_rst_mig_7series_0_81M_0/eth_mac_test_rst_mig_7series_0_81M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==eth_mac_test_rst_mig_7series_0_81M_0} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_axi_timer_0_0/eth_mac_test_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_axi_timer_0_0 || ORIG_REF_NAME==eth_mac_test_axi_timer_0_0} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_axi_uartlite_0_0/eth_mac_test_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_axi_uartlite_0_0 || ORIG_REF_NAME==eth_mac_test_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_clk_wiz_0_1/eth_mac_test_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_clk_wiz_0_1 || ORIG_REF_NAME==eth_mac_test_clk_wiz_0_1} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_auto_pc_5/eth_mac_test_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_auto_pc_5 || ORIG_REF_NAME==eth_mac_test_auto_pc_5} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_auto_us_0/eth_mac_test_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_auto_us_0 || ORIG_REF_NAME==eth_mac_test_auto_us_0} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_auto_us_1/eth_mac_test_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_auto_us_1 || ORIG_REF_NAME==eth_mac_test_auto_us_1} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_auto_us_2/eth_mac_test_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_auto_us_2 || ORIG_REF_NAME==eth_mac_test_auto_us_2} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_auto_ds_0/eth_mac_test_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_auto_ds_0 || ORIG_REF_NAME==eth_mac_test_auto_ds_0} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_auto_pc_0/eth_mac_test_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_auto_pc_0 || ORIG_REF_NAME==eth_mac_test_auto_pc_0} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_auto_ds_1/eth_mac_test_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_auto_ds_1 || ORIG_REF_NAME==eth_mac_test_auto_ds_1} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_auto_pc_1/eth_mac_test_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_auto_pc_1 || ORIG_REF_NAME==eth_mac_test_auto_pc_1} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_auto_ds_2/eth_mac_test_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_auto_ds_2 || ORIG_REF_NAME==eth_mac_test_auto_ds_2} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_auto_pc_2/eth_mac_test_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_auto_pc_2 || ORIG_REF_NAME==eth_mac_test_auto_pc_2} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_auto_ds_3/eth_mac_test_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_auto_ds_3 || ORIG_REF_NAME==eth_mac_test_auto_ds_3} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_auto_pc_3/eth_mac_test_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_auto_pc_3 || ORIG_REF_NAME==eth_mac_test_auto_pc_3} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_auto_ds_4/eth_mac_test_auto_ds_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_auto_ds_4 || ORIG_REF_NAME==eth_mac_test_auto_ds_4} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_auto_pc_4/eth_mac_test_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_auto_pc_4 || ORIG_REF_NAME==eth_mac_test_auto_pc_4} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_axi_ethernet_0_0/eth_mac_test_axi_ethernet_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_axi_ethernet_0_0 || ORIG_REF_NAME==eth_mac_test_axi_ethernet_0_0} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_axi_ethernet_0_fifo_0/eth_mac_test_axi_ethernet_0_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_axi_ethernet_0_fifo_0 || ORIG_REF_NAME==eth_mac_test_axi_ethernet_0_fifo_0} -quiet] -quiet

# IP: bd/eth_mac_test/ip/eth_mac_test_axi_ethernet_0_gtxclk_0/eth_mac_test_axi_ethernet_0_gtxclk_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_test_axi_ethernet_0_gtxclk_0 || ORIG_REF_NAME==eth_mac_test_axi_ethernet_0_gtxclk_0} -quiet] -quiet

# XDC: c:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/ARTY_ETH/ARTY_ETH.gen/sources_1/bd/eth_mac_test/eth_mac_test_ooc.xdc
