# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/ARTY_ETH/ARTY_ETH.srcs/sources_1/bd/design_2_udp/ip/design_2_udp_clk_wiz_1_0/design_2_udp_clk_wiz_1_0.xci
# IP: The module: 'design_2_udp_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/ARTY_ETH/ARTY_ETH.gen/sources_1/bd/design_2_udp/ip/design_2_udp_clk_wiz_1_0/design_2_udp_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_udp_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/ARTY_ETH/ARTY_ETH.gen/sources_1/bd/design_2_udp/ip/design_2_udp_clk_wiz_1_0/design_2_udp_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_udp_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/ARTY_ETH/ARTY_ETH.gen/sources_1/bd/design_2_udp/ip/design_2_udp_clk_wiz_1_0/design_2_udp_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_udp_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/ARTY_ETH/ARTY_ETH.srcs/sources_1/bd/design_2_udp/ip/design_2_udp_clk_wiz_1_0/design_2_udp_clk_wiz_1_0.xci
# IP: The module: 'design_2_udp_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/ARTY_ETH/ARTY_ETH.gen/sources_1/bd/design_2_udp/ip/design_2_udp_clk_wiz_1_0/design_2_udp_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_udp_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/ARTY_ETH/ARTY_ETH.gen/sources_1/bd/design_2_udp/ip/design_2_udp_clk_wiz_1_0/design_2_udp_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_udp_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/ARTY_ETH/ARTY_ETH.gen/sources_1/bd/design_2_udp/ip/design_2_udp_clk_wiz_1_0/design_2_udp_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_udp_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
