# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/project_2/project_2.srcs/sources_1/bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_lmb_bram_0/arty_adc_eth_v4_lmb_bram_0.xci
# IP: The module: 'arty_adc_eth_v4_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/project_2/project_2.gen/sources_1/bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_lmb_bram_0/arty_adc_eth_v4_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_adc_eth_v4_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/project_2/project_2.srcs/sources_1/bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_lmb_bram_0/arty_adc_eth_v4_lmb_bram_0.xci
# IP: The module: 'arty_adc_eth_v4_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/project_2/project_2.gen/sources_1/bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_lmb_bram_0/arty_adc_eth_v4_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_adc_eth_v4_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
