# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/project_2/project_2.srcs/sources_1/bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_xadc_wiz_0_0/arty_adc_eth_v4_xadc_wiz_0_0.xci
# IP: The module: 'arty_adc_eth_v4_xadc_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/project_2/project_2.gen/sources_1/bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_xadc_wiz_0_0/arty_adc_eth_v4_xadc_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_adc_eth_v4_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/project_2/project_2.gen/sources_1/bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_xadc_wiz_0_0/arty_adc_eth_v4_xadc_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_adc_eth_v4_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/project_2/project_2.srcs/sources_1/bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_xadc_wiz_0_0/arty_adc_eth_v4_xadc_wiz_0_0.xci
# IP: The module: 'arty_adc_eth_v4_xadc_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/project_2/project_2.gen/sources_1/bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_xadc_wiz_0_0/arty_adc_eth_v4_xadc_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_adc_eth_v4_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Bruker/Documents/Bachelor_Elektro_ingenior_med_auto/fpga/project_2/project_2.gen/sources_1/bd/arty_adc_eth_v4/ip/arty_adc_eth_v4_xadc_wiz_0_0/arty_adc_eth_v4_xadc_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_adc_eth_v4_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
